empleado:
    pattern:  /
    defaults: { _controller: "PanelBundle:Empleado:index" }

empleado_show:
    pattern:  /show/{id}
    defaults: { _controller: "PanelBundle:Empleado:show" }

empleado_new:
    pattern:  /new
    defaults: { _controller: "PanelBundle:Empleado:new" }

empleado_create:
    pattern:  /create
    defaults: { _controller: "PanelBundle:Empleado:create" }
    requirements: { _method: post }

empleado_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "PanelBundle:Empleado:edit" }

empleado_update:
    pattern:  /update/{id}
    defaults: { _controller: "PanelBundle:Empleado:update" }
    requirements: { _method: post }

empleado_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "PanelBundle:Empleado:delete" }

empleado_paginas:
    pattern:  /paginas/{page}
    defaults: { _controller: "PanelBundle:default:index" }